/*
 * generated by Xtext
 */
package ac.soton.xtext.iumlb;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends ac.soton.xtext.iumlb.AbstractDslRuntimeModule {

}
