/*
* generated by Xtext
*/
package ac.soton.xtext.iumlb.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ac/soton/xtext/iumlb/parser/antlr/internal/InternalDsl.tokens");
	}
}
