/**
 * generated by Xtext
 */
package ac.soton.xtext.machine.dsl.serializer;

import ac.soton.xtext.machine.dsl.serializer.AbstractMachineDslSyntacticSequencer;

@SuppressWarnings("all")
public class MachineDslSyntacticSequencer extends AbstractMachineDslSyntacticSequencer {
}
