/**
 * generated by Xtext
 */
package ac.soton.xtext.machine.dsl.serializer;

import ac.soton.xtext.machine.dsl.serializer.AbstractMachineDslSemanticSequencer;

@SuppressWarnings("all")
public class MachineDslSemanticSequencer extends AbstractMachineDslSemanticSequencer {
}
