/**
 * generated by Xtext
 */
package ac.soton.xtext.serializer;

import ac.soton.xtext.serializer.AbstractMachineDslSyntacticSequencer;

@SuppressWarnings("all")
public class MachineDslSyntacticSequencer extends AbstractMachineDslSyntacticSequencer {
}
