/*
* generated by Xtext
*/
package ac.soton.xtext.machine.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MachineDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ac.soton.xtext.machine.dsl.ui.internal.MachineDslActivator.getInstance().getInjector("ac.soton.xtext.machine.dsl.MachineDsl");
	}
	
}
