/**
 * generated by Xtext
 */
package ac.soton.xtext.serializer;

import ac.soton.xtext.serializer.AbstractContextDslSemanticSequencer;

@SuppressWarnings("all")
public class ContextDslSemanticSequencer extends AbstractContextDslSemanticSequencer {
}
