/**
 * generated by Xtext
 */
package ac.soton.xtext.serializer;

import ac.soton.xtext.serializer.AbstractContextDslSyntacticSequencer;

@SuppressWarnings("all")
public class ContextDslSyntacticSequencer extends AbstractContextDslSyntacticSequencer {
}
