/*
 * generated by Xtext
 */
package ac.soton.xtext.iumlb.ui.contentassist

import ac.soton.xtext.iumlb.ui.contentassist.AbstractDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DslProposalProvider extends AbstractDslProposalProvider {
}
