/*
 * generated by Xtext
 */
package ac.soton.xtext.machine.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMachineDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://emf.eventb.org/models/core/machine/2014"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://emf.eventb.org/models/core/2014"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://emf.eventb.org/models/core/context/2014"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/emf/2002/Ecore"));
		return result;
	}
}
