/*
* generated by Xtext
*/
package ac.soton.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import ac.soton.xtext.services.MachineDslGrammarAccess;

public class MachineDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MachineDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected ac.soton.xtext.ui.contentassist.antlr.internal.InternalMachineDslParser createParser() {
		ac.soton.xtext.ui.contentassist.antlr.internal.InternalMachineDslParser result = new ac.soton.xtext.ui.contentassist.antlr.internal.InternalMachineDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getAttributeTypeAccess().getAlternatives(), "rule__AttributeType__Alternatives");
					put(grammarAccess.getConvergenceAccess().getAlternatives(), "rule__Convergence__Alternatives");
					put(grammarAccess.getMachineAccess().getGroup(), "rule__Machine__Group__0");
					put(grammarAccess.getMachineAccess().getGroup_3(), "rule__Machine__Group_3__0");
					put(grammarAccess.getMachineAccess().getGroup_4(), "rule__Machine__Group_4__0");
					put(grammarAccess.getMachineAccess().getGroup_4_2(), "rule__Machine__Group_4_2__0");
					put(grammarAccess.getMachineAccess().getGroup_5(), "rule__Machine__Group_5__0");
					put(grammarAccess.getMachineAccess().getGroup_5_3(), "rule__Machine__Group_5_3__0");
					put(grammarAccess.getMachineAccess().getGroup_6(), "rule__Machine__Group_6__0");
					put(grammarAccess.getMachineAccess().getGroup_6_2(), "rule__Machine__Group_6_2__0");
					put(grammarAccess.getMachineAccess().getGroup_7(), "rule__Machine__Group_7__0");
					put(grammarAccess.getMachineAccess().getGroup_8(), "rule__Machine__Group_8__0");
					put(grammarAccess.getMachineAccess().getGroup_9(), "rule__Machine__Group_9__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup_3(), "rule__Annotation__Group_3__0");
					put(grammarAccess.getAnnotationAccess().getGroup_4(), "rule__Annotation__Group_4__0");
					put(grammarAccess.getAnnotationAccess().getGroup_4_3(), "rule__Annotation__Group_4_3__0");
					put(grammarAccess.getAnnotationAccess().getGroup_5(), "rule__Annotation__Group_5__0");
					put(grammarAccess.getAnnotationAccess().getGroup_5_3(), "rule__Annotation__Group_5_3__0");
					put(grammarAccess.getAnnotationAccess().getGroup_6(), "rule__Annotation__Group_6__0");
					put(grammarAccess.getAnnotationAccess().getGroup_6_3(), "rule__Annotation__Group_6_3__0");
					put(grammarAccess.getAnnotationAccess().getGroup_7(), "rule__Annotation__Group_7__0");
					put(grammarAccess.getAnnotationAccess().getGroup_7_3(), "rule__Annotation__Group_7_3__0");
					put(grammarAccess.getStringToAttributeMapEntryAccess().getGroup(), "rule__StringToAttributeMapEntry__Group__0");
					put(grammarAccess.getStringToAttributeMapEntryAccess().getGroup_4(), "rule__StringToAttributeMapEntry__Group_4__0");
					put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
					put(grammarAccess.getVariableAccess().getGroup_2(), "rule__Variable__Group_2__0");
					put(grammarAccess.getInvariantAccess().getGroup(), "rule__Invariant__Group__0");
					put(grammarAccess.getInvariantAccess().getGroup_5(), "rule__Invariant__Group_5__0");
					put(grammarAccess.getVariantAccess().getGroup(), "rule__Variant__Group__0");
					put(grammarAccess.getVariantAccess().getGroup_3(), "rule__Variant__Group_3__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getEventAccess().getGroup_5(), "rule__Event__Group_5__0");
					put(grammarAccess.getEventAccess().getGroup_6(), "rule__Event__Group_6__0");
					put(grammarAccess.getEventAccess().getGroup_6_2(), "rule__Event__Group_6_2__0");
					put(grammarAccess.getEventAccess().getGroup_7(), "rule__Event__Group_7__0");
					put(grammarAccess.getEventAccess().getGroup_7_2(), "rule__Event__Group_7_2__0");
					put(grammarAccess.getEventAccess().getGroup_8(), "rule__Event__Group_8__0");
					put(grammarAccess.getEventAccess().getGroup_9(), "rule__Event__Group_9__0");
					put(grammarAccess.getEventAccess().getGroup_10(), "rule__Event__Group_10__0");
					put(grammarAccess.getStringToStringMapEntryAccess().getGroup(), "rule__StringToStringMapEntry__Group__0");
					put(grammarAccess.getStringToStringMapEntryAccess().getGroup_3(), "rule__StringToStringMapEntry__Group_3__0");
					put(grammarAccess.getStringToStringMapEntryAccess().getGroup_4(), "rule__StringToStringMapEntry__Group_4__0");
					put(grammarAccess.getEObjectAccess().getGroup(), "rule__EObject__Group__0");
					put(grammarAccess.getExtensionAccess().getGroup(), "rule__Extension__Group__0");
					put(grammarAccess.getExtensionAccess().getGroup_2(), "rule__Extension__Group_2__0");
					put(grammarAccess.getExtensionAccess().getGroup_5(), "rule__Extension__Group_5__0");
					put(grammarAccess.getExtensionAccess().getGroup_5_3(), "rule__Extension__Group_5_3__0");
					put(grammarAccess.getExtensionAccess().getGroup_6(), "rule__Extension__Group_6__0");
					put(grammarAccess.getExtensionAccess().getGroup_6_3(), "rule__Extension__Group_6_3__0");
					put(grammarAccess.getExtensionAccess().getGroup_7(), "rule__Extension__Group_7__0");
					put(grammarAccess.getExtensionAccess().getGroup_7_3(), "rule__Extension__Group_7_3__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_5(), "rule__Attribute__Group_5__0");
					put(grammarAccess.getAttributeAccess().getGroup_5_3(), "rule__Attribute__Group_5_3__0");
					put(grammarAccess.getCarrierSetAccess().getGroup(), "rule__CarrierSet__Group__0");
					put(grammarAccess.getCarrierSetAccess().getGroup_4(), "rule__CarrierSet__Group_4__0");
					put(grammarAccess.getConstantAccess().getGroup(), "rule__Constant__Group__0");
					put(grammarAccess.getConstantAccess().getGroup_5(), "rule__Constant__Group_5__0");
					put(grammarAccess.getConstantAccess().getGroup_6(), "rule__Constant__Group_6__0");
					put(grammarAccess.getConstantAccess().getGroup_7(), "rule__Constant__Group_7__0");
					put(grammarAccess.getConstantAccess().getGroup_7_3(), "rule__Constant__Group_7_3__0");
					put(grammarAccess.getConstantAccess().getGroup_8(), "rule__Constant__Group_8__0");
					put(grammarAccess.getConstantAccess().getGroup_8_3(), "rule__Constant__Group_8_3__0");
					put(grammarAccess.getConstantAccess().getGroup_9(), "rule__Constant__Group_9__0");
					put(grammarAccess.getConstantAccess().getGroup_9_3(), "rule__Constant__Group_9_3__0");
					put(grammarAccess.getAxiomAccess().getGroup(), "rule__Axiom__Group__0");
					put(grammarAccess.getAxiomAccess().getGroup_4(), "rule__Axiom__Group_4__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_2(), "rule__Parameter__Group_2__0");
					put(grammarAccess.getGuardAccess().getGroup(), "rule__Guard__Group__0");
					put(grammarAccess.getGuardAccess().getGroup_5(), "rule__Guard__Group_5__0");
					put(grammarAccess.getWitnessAccess().getGroup(), "rule__Witness__Group__0");
					put(grammarAccess.getWitnessAccess().getGroup_6(), "rule__Witness__Group_6__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
					put(grammarAccess.getMachineAccess().getNameAssignment_2(), "rule__Machine__NameAssignment_2");
					put(grammarAccess.getMachineAccess().getCommentAssignment_3_1(), "rule__Machine__CommentAssignment_3_1");
					put(grammarAccess.getMachineAccess().getRefinesAssignment_4_1(), "rule__Machine__RefinesAssignment_4_1");
					put(grammarAccess.getMachineAccess().getRefinesAssignment_4_2_1(), "rule__Machine__RefinesAssignment_4_2_1");
					put(grammarAccess.getMachineAccess().getSeesAssignment_5_2(), "rule__Machine__SeesAssignment_5_2");
					put(grammarAccess.getMachineAccess().getSeesAssignment_5_3_1(), "rule__Machine__SeesAssignment_5_3_1");
					put(grammarAccess.getMachineAccess().getVariablesAssignment_6_1(), "rule__Machine__VariablesAssignment_6_1");
					put(grammarAccess.getMachineAccess().getVariablesAssignment_6_2_1(), "rule__Machine__VariablesAssignment_6_2_1");
					put(grammarAccess.getMachineAccess().getInvariantsAssignment_7_1(), "rule__Machine__InvariantsAssignment_7_1");
					put(grammarAccess.getMachineAccess().getInvariantsAssignment_7_2(), "rule__Machine__InvariantsAssignment_7_2");
					put(grammarAccess.getMachineAccess().getVariantAssignment_8_1(), "rule__Machine__VariantAssignment_8_1");
					put(grammarAccess.getMachineAccess().getEventsAssignment_9_1(), "rule__Machine__EventsAssignment_9_1");
					put(grammarAccess.getMachineAccess().getEventsAssignment_9_2(), "rule__Machine__EventsAssignment_9_2");
					put(grammarAccess.getAnnotationAccess().getSourceAssignment_3_1(), "rule__Annotation__SourceAssignment_3_1");
					put(grammarAccess.getAnnotationAccess().getReferencesAssignment_4_2(), "rule__Annotation__ReferencesAssignment_4_2");
					put(grammarAccess.getAnnotationAccess().getReferencesAssignment_4_3_1(), "rule__Annotation__ReferencesAssignment_4_3_1");
					put(grammarAccess.getAnnotationAccess().getAnnotationsAssignment_5_2(), "rule__Annotation__AnnotationsAssignment_5_2");
					put(grammarAccess.getAnnotationAccess().getAnnotationsAssignment_5_3_1(), "rule__Annotation__AnnotationsAssignment_5_3_1");
					put(grammarAccess.getAnnotationAccess().getDetailsAssignment_6_2(), "rule__Annotation__DetailsAssignment_6_2");
					put(grammarAccess.getAnnotationAccess().getDetailsAssignment_6_3_1(), "rule__Annotation__DetailsAssignment_6_3_1");
					put(grammarAccess.getAnnotationAccess().getContentsAssignment_7_2(), "rule__Annotation__ContentsAssignment_7_2");
					put(grammarAccess.getAnnotationAccess().getContentsAssignment_7_3_1(), "rule__Annotation__ContentsAssignment_7_3_1");
					put(grammarAccess.getStringToAttributeMapEntryAccess().getKeyAssignment_3(), "rule__StringToAttributeMapEntry__KeyAssignment_3");
					put(grammarAccess.getStringToAttributeMapEntryAccess().getValueAssignment_4_1(), "rule__StringToAttributeMapEntry__ValueAssignment_4_1");
					put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
					put(grammarAccess.getVariableAccess().getCommentAssignment_2_1(), "rule__Variable__CommentAssignment_2_1");
					put(grammarAccess.getInvariantAccess().getNameAssignment_1(), "rule__Invariant__NameAssignment_1");
					put(grammarAccess.getInvariantAccess().getTheoremAssignment_2(), "rule__Invariant__TheoremAssignment_2");
					put(grammarAccess.getInvariantAccess().getPredicateAssignment_4(), "rule__Invariant__PredicateAssignment_4");
					put(grammarAccess.getInvariantAccess().getCommentAssignment_5_1(), "rule__Invariant__CommentAssignment_5_1");
					put(grammarAccess.getVariantAccess().getExpressionAssignment_2(), "rule__Variant__ExpressionAssignment_2");
					put(grammarAccess.getVariantAccess().getCommentAssignment_3_1(), "rule__Variant__CommentAssignment_3_1");
					put(grammarAccess.getEventAccess().getNameAssignment_2(), "rule__Event__NameAssignment_2");
					put(grammarAccess.getEventAccess().getExtendedAssignment_3(), "rule__Event__ExtendedAssignment_3");
					put(grammarAccess.getEventAccess().getConvergenceAssignment_4(), "rule__Event__ConvergenceAssignment_4");
					put(grammarAccess.getEventAccess().getCommentAssignment_5_1(), "rule__Event__CommentAssignment_5_1");
					put(grammarAccess.getEventAccess().getRefinesAssignment_6_1(), "rule__Event__RefinesAssignment_6_1");
					put(grammarAccess.getEventAccess().getRefinesAssignment_6_2_1(), "rule__Event__RefinesAssignment_6_2_1");
					put(grammarAccess.getEventAccess().getParametersAssignment_7_1(), "rule__Event__ParametersAssignment_7_1");
					put(grammarAccess.getEventAccess().getParametersAssignment_7_2_1(), "rule__Event__ParametersAssignment_7_2_1");
					put(grammarAccess.getEventAccess().getGuardsAssignment_8_0(), "rule__Event__GuardsAssignment_8_0");
					put(grammarAccess.getEventAccess().getGuardsAssignment_8_1(), "rule__Event__GuardsAssignment_8_1");
					put(grammarAccess.getEventAccess().getWitnessesAssignment_9_1(), "rule__Event__WitnessesAssignment_9_1");
					put(grammarAccess.getEventAccess().getWitnessesAssignment_9_2(), "rule__Event__WitnessesAssignment_9_2");
					put(grammarAccess.getEventAccess().getActionsAssignment_10_0(), "rule__Event__ActionsAssignment_10_0");
					put(grammarAccess.getEventAccess().getActionsAssignment_10_1(), "rule__Event__ActionsAssignment_10_1");
					put(grammarAccess.getStringToStringMapEntryAccess().getKeyAssignment_3_1(), "rule__StringToStringMapEntry__KeyAssignment_3_1");
					put(grammarAccess.getStringToStringMapEntryAccess().getValueAssignment_4_1(), "rule__StringToStringMapEntry__ValueAssignment_4_1");
					put(grammarAccess.getExtensionAccess().getLocalGeneratedAssignment_0(), "rule__Extension__LocalGeneratedAssignment_0");
					put(grammarAccess.getExtensionAccess().getInternalIdAssignment_2_1(), "rule__Extension__InternalIdAssignment_2_1");
					put(grammarAccess.getExtensionAccess().getExtensionIdAssignment_4(), "rule__Extension__ExtensionIdAssignment_4");
					put(grammarAccess.getExtensionAccess().getAnnotationsAssignment_5_2(), "rule__Extension__AnnotationsAssignment_5_2");
					put(grammarAccess.getExtensionAccess().getAnnotationsAssignment_5_3_1(), "rule__Extension__AnnotationsAssignment_5_3_1");
					put(grammarAccess.getExtensionAccess().getExtensionsAssignment_6_2(), "rule__Extension__ExtensionsAssignment_6_2");
					put(grammarAccess.getExtensionAccess().getExtensionsAssignment_6_3_1(), "rule__Extension__ExtensionsAssignment_6_3_1");
					put(grammarAccess.getExtensionAccess().getAttributesAssignment_7_2(), "rule__Extension__AttributesAssignment_7_2");
					put(grammarAccess.getExtensionAccess().getAttributesAssignment_7_3_1(), "rule__Extension__AttributesAssignment_7_3_1");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
					put(grammarAccess.getAttributeAccess().getValueAssignment_4(), "rule__Attribute__ValueAssignment_4");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_5_2(), "rule__Attribute__AnnotationsAssignment_5_2");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_5_3_1(), "rule__Attribute__AnnotationsAssignment_5_3_1");
					put(grammarAccess.getCarrierSetAccess().getLocalGeneratedAssignment_1(), "rule__CarrierSet__LocalGeneratedAssignment_1");
					put(grammarAccess.getCarrierSetAccess().getNameAssignment_3(), "rule__CarrierSet__NameAssignment_3");
					put(grammarAccess.getCarrierSetAccess().getCommentAssignment_4_1(), "rule__CarrierSet__CommentAssignment_4_1");
					put(grammarAccess.getConstantAccess().getLocalGeneratedAssignment_1(), "rule__Constant__LocalGeneratedAssignment_1");
					put(grammarAccess.getConstantAccess().getNameAssignment_3(), "rule__Constant__NameAssignment_3");
					put(grammarAccess.getConstantAccess().getInternalIdAssignment_5_1(), "rule__Constant__InternalIdAssignment_5_1");
					put(grammarAccess.getConstantAccess().getCommentAssignment_6_1(), "rule__Constant__CommentAssignment_6_1");
					put(grammarAccess.getConstantAccess().getAnnotationsAssignment_7_2(), "rule__Constant__AnnotationsAssignment_7_2");
					put(grammarAccess.getConstantAccess().getAnnotationsAssignment_7_3_1(), "rule__Constant__AnnotationsAssignment_7_3_1");
					put(grammarAccess.getConstantAccess().getExtensionsAssignment_8_2(), "rule__Constant__ExtensionsAssignment_8_2");
					put(grammarAccess.getConstantAccess().getExtensionsAssignment_8_3_1(), "rule__Constant__ExtensionsAssignment_8_3_1");
					put(grammarAccess.getConstantAccess().getAttributesAssignment_9_2(), "rule__Constant__AttributesAssignment_9_2");
					put(grammarAccess.getConstantAccess().getAttributesAssignment_9_3_1(), "rule__Constant__AttributesAssignment_9_3_1");
					put(grammarAccess.getAxiomAccess().getTheoremAssignment_0(), "rule__Axiom__TheoremAssignment_0");
					put(grammarAccess.getAxiomAccess().getNameAssignment_3(), "rule__Axiom__NameAssignment_3");
					put(grammarAccess.getAxiomAccess().getCommentAssignment_4_1(), "rule__Axiom__CommentAssignment_4_1");
					put(grammarAccess.getAxiomAccess().getPredicateAssignment_6(), "rule__Axiom__PredicateAssignment_6");
					put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
					put(grammarAccess.getParameterAccess().getCommentAssignment_2_1(), "rule__Parameter__CommentAssignment_2_1");
					put(grammarAccess.getGuardAccess().getNameAssignment_1(), "rule__Guard__NameAssignment_1");
					put(grammarAccess.getGuardAccess().getTheoremAssignment_2(), "rule__Guard__TheoremAssignment_2");
					put(grammarAccess.getGuardAccess().getPredicateAssignment_4(), "rule__Guard__PredicateAssignment_4");
					put(grammarAccess.getGuardAccess().getCommentAssignment_5_1(), "rule__Guard__CommentAssignment_5_1");
					put(grammarAccess.getWitnessAccess().getLocalGeneratedAssignment_0(), "rule__Witness__LocalGeneratedAssignment_0");
					put(grammarAccess.getWitnessAccess().getNameAssignment_3(), "rule__Witness__NameAssignment_3");
					put(grammarAccess.getWitnessAccess().getPredicateAssignment_5(), "rule__Witness__PredicateAssignment_5");
					put(grammarAccess.getWitnessAccess().getCommentAssignment_6_1(), "rule__Witness__CommentAssignment_6_1");
					put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
					put(grammarAccess.getActionAccess().getActionAssignment_3(), "rule__Action__ActionAssignment_3");
					put(grammarAccess.getActionAccess().getCommentAssignment_4_1(), "rule__Action__CommentAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			ac.soton.xtext.ui.contentassist.antlr.internal.InternalMachineDslParser typedParser = (ac.soton.xtext.ui.contentassist.antlr.internal.InternalMachineDslParser) parser;
			typedParser.entryRuleMachine();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MachineDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MachineDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
