/*
 * generated by Xtext
 */
package ac.soton.xtext.machine.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MachineDslRuntimeModule extends ac.soton.xtext.machine.dsl.AbstractMachineDslRuntimeModule {

}
