package org.eventb.codegen.templates.impl;

import java.util.ArrayList;
import java.util.List;

import org.eventb.codegen.templates.AbstractGenerator;

public class FmiInstantiateGenerator extends AbstractGenerator {
	// TODO This key's initial value should be obtained from 
	// the extension, and .
	private String key = "fmiInstantiate";
	
	@Override
	public List<String> generate() {
		List<String> outCode = new ArrayList<String>();
		outCode.add("// Generated By FMIInsantiateGenerator");
		return outCode;
	}
	
	@Override
	public String getKey() {
		return key;
	}
	
	@Override
	public void setKey(String key) {
		super.setKey(key);
	}

}
