/*
 * generated by Xtext
 */
package ac.soton.xtext.machine.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MachineDslUiModule extends ac.soton.xtext.machine.dsl.ui.AbstractMachineDslUiModule {
	public MachineDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
