/**
 * generated by Xtext
 */
package ac.soton.xtext.validation;

import ac.soton.xtext.validation.AbstractMachineDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MachineDslValidator extends AbstractMachineDslValidator {
}
