/**
 * generated by Xtext
 */
package ac.soton.xtext.context.dsl.ui.contentassist;

import ac.soton.xtext.context.dsl.ui.contentassist.AbstractContextDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ContextDslProposalProvider extends AbstractContextDslProposalProvider {
}
