/**
 * generated by Xtext
 */
package ac.soton.xtext.context.dsl.serializer;

import ac.soton.xtext.context.dsl.serializer.AbstractContextDslSemanticSequencer;

@SuppressWarnings("all")
public class ContextDslSemanticSequencer extends AbstractContextDslSemanticSequencer {
}
